# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CarRental' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for CarRental
  # Required by RNFirebase
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'CarRental-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'CarRentalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
